FROM balenalib/aarch64-python:3.9
COPY ./qemu-arm-static /usr/bin/qemu-arm-static
RUN apt update
RUN apt install -y chromium chromium-driver locales locales-all

ENV LC_ALL it_IT.UTF-8
ENV LANG it_IT.UTF-8
ENV LANGUAGE it_IT.UTF-8

WORKDIR /
ARG requirements=requirements.txt
COPY $requirements /src/requirements.txt
RUN pip install -r /src/requirements.txt
COPY VERSION /src/version.txt
COPY src /src

ENTRYPOINT ["bash", "/src/run.bash"]
